name: example-environment
channels:
  - conda-forge
  - conda-forge/label/jupyterlab_alpha
  - nodefaults
dependencies:
  - jupyterlab >=4.0.0a34
  - jupyterlab-link-share >=0.2
  - nodejs >=18,<19
  - python >=3.11,<3.12
  - yarn <2
  # build
  - hatchling >=1.5.0
  - hatch-jupyter-builder >=0.3.2
  - hatch-nodejs-version
  # dependencies
  - jupyter_server >=2.0.0
  # Use pip to get the the latest version
  - pip:
    - jupyter_server_fileid >=0.7.0
    - jupyter_ydoc >=1.0.0
    - ypy-websocket >=0.8.3
