name: example-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupyterlab >=4.6.0
  - nodejs >=24,<25
  - python=3.11
  - yarn >=3,<4
  # build
  - hatchling >=1.5.0
  - hatch-jupyter-builder >=0.5
  - hatch-nodejs-version
  - jupyter-builder >=1.2.0
  # dependencies
  - jupyter_server >=2.0.0
